" vim-plug
set nocompatible
filetype off
" set the runtime path to include Vundle and initialize
call plug#begin()
    Plug 'scrooloose/nerdtree'
    Plug 'bling/vim-airline'
    Plug 'altercation/vim-colors-solarized'
    Plug 'rakr/vim-one'
    Plug 'joshdick/onedark.vim'
    Plug 'sheerun/vim-polyglot'
    Plug 'moll/vim-node'
    Plug 'flazz/vim-colorschemes'
    Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
    Plug 'jceb/vim-orgmode'
    Plug 'fatih/vim-go', {'do': ':GoUpdateBinaries'}
    Plug 'rust-lang/rust.vim'
    Plug 'majutsushi/tagbar'
    Plug 'bagrat/vim-buffet'
    
call plug#end()
filetype plugin indent on
" To ignore plugin indent changes, instead use:
" filetype plugin on

" NERDTree
map <F3> :NERDTreeToggle<CR>

set tabstop=4 
set softtabstop=4 
set shiftwidth=4 
set expandtab 
set nu 
set autoindent
set cindent
let &termencoding=&encoding
set number
set encoding=utf-8
set fileencodings=utf-8,gbk,gb18030,gk2312
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
"language messages zh_CN.utf-8
set showmatch
set incsearch
set clipboard+=unnamed
set ruler
syntax enable
"
" set color theme
"
"Credit joshdick
"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
"if (empty($TMUX))
"  if (has("nvim"))
"  "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
"  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
"  endif
"  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
"  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
"  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
"  if (has("termguicolors"))
"    set termguicolors
"  endif
"endif

colorscheme onedark
"colorscheme solarized

let g:one_allow_italics = 1
let g:airline_theme='onedark'


set guifont=Ubuntu\ Mono
let g:rustfmt_autosave=1
nmap <F8> :TagbarToggle<CR>

noremap <Tab> :bn<CR>
noremap <S-Tab> :bp<CR>
noremap <Leader><Tab> :Bw<CR>
noremap <Leader><S-Tab> :Bw!<CR>
noremap <C-t> :tabnew split<CR>
let g:buffet_show_index = 1
